//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Clima {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Clima.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows us that.
        /// </summary>
        public static string ClimatologyContentEnd {
            get {
                return ResourceManager.GetString("ClimatologyContentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The climatology for.
        /// </summary>
        public static string ClimatologyContentStart {
            get {
                return ResourceManager.GetString("ClimatologyContentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the weather station.
        /// </summary>
        public static string ClimatologyContentWS {
            get {
                return ResourceManager.GetString("ClimatologyContentWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average of the last 30 years for each month.
        /// </summary>
        public static string ClimatologyDescriptionEnd {
            get {
                return ResourceManager.GetString("ClimatologyDescriptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These plot shows.
        /// </summary>
        public static string ClimatologyDescriptionStart {
            get {
                return ResourceManager.GetString("ClimatologyDescriptionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month with highest value is.
        /// </summary>
        public static string ClimatologyIndicatorHighest {
            get {
                return ResourceManager.GetString("ClimatologyIndicatorHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month with lowest value is.
        /// </summary>
        public static string ClimatologyIndicatorLowest {
            get {
                return ResourceManager.GetString("ClimatologyIndicatorLowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly historical average of.
        /// </summary>
        public static string ClimatologyTitle {
            get {
                return ResourceManager.GetString("ClimatologyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string ClimatologyXAxis {
            get {
                return ResourceManager.GetString("ClimatologyXAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to above normal.
        /// </summary>
        public static string ForecastAbove {
            get {
                return ResourceManager.GetString("ForecastAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below normal.
        /// </summary>
        public static string ForecastBelow {
            get {
                return ResourceManager.GetString("ForecastBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The climate prediction is given in percentage of probability with respect to the normal range of precipitation of an area and a specific quarter. Below, you can find the most probable category for the selected municipality and the forecast quarter..
        /// </summary>
        public static string ForecastExplanation {
            get {
                return ResourceManager.GetString("ForecastExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weather forecast is presented, for the city.
        /// </summary>
        public static string ForecastMunicipality {
            get {
                return ResourceManager.GetString("ForecastMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inside normal.
        /// </summary>
        public static string ForecastNormal {
            get {
                return ResourceManager.GetString("ForecastNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for the period between.
        /// </summary>
        public static string ForecastPeriod {
            get {
                return ResourceManager.GetString("ForecastPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation probabilities (%).
        /// </summary>
        public static string ForecastProbabilitiesTitle {
            get {
                return ResourceManager.GetString("ForecastProbabilitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string ForecastScenarioAvg {
            get {
                return ResourceManager.GetString("ForecastScenarioAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ForecastScenarioDate {
            get {
                return ResourceManager.GetString("ForecastScenarioDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximun.
        /// </summary>
        public static string ForecastScenarioMaximun {
            get {
                return ResourceManager.GetString("ForecastScenarioMaximun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimun.
        /// </summary>
        public static string ForecastScenarioMinimun {
            get {
                return ResourceManager.GetString("ForecastScenarioMinimun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction scenarios.
        /// </summary>
        public static string ForecastScenarioTitle {
            get {
                return ResourceManager.GetString("ForecastScenarioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the quarter.
        /// </summary>
        public static string ForecastSummaryMonth {
            get {
                return ResourceManager.GetString("ForecastSummaryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal precipitation is between.
        /// </summary>
        public static string ForecastSummaryNormal {
            get {
                return ResourceManager.GetString("ForecastSummaryNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the climate forecast suggests that precipitation is most likely.
        /// </summary>
        public static string ForecastSummaryResult {
            get {
                return ResourceManager.GetString("ForecastSummaryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the municipality.
        /// </summary>
        public static string ForecastSummaryWS {
            get {
                return ResourceManager.GetString("ForecastSummaryWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate forecast.
        /// </summary>
        public static string ForecastTitle {
            get {
                return ResourceManager.GetString("ForecastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference weather station to make this predictions was.
        /// </summary>
        public static string ForecastWS {
            get {
                return ResourceManager.GetString("ForecastWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provided by.
        /// </summary>
        public static string ForecastWSProvider {
            get {
                return ResourceManager.GetString("ForecastWSProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it presents the following behavior.
        /// </summary>
        public static string HistoricalContentEnd {
            get {
                return ResourceManager.GetString("HistoricalContentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the weather station.
        /// </summary>
        public static string HistoricalContentMid {
            get {
                return ResourceManager.GetString("HistoricalContentMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historically in the municipality of.
        /// </summary>
        public static string HistoricalContentStart {
            get {
                return ResourceManager.GetString("HistoricalContentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can filter the month of interest by clicking on the category.
        /// </summary>
        public static string HistoricalDescriptionEnd {
            get {
                return ResourceManager.GetString("HistoricalDescriptionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plot shows the historical values of.
        /// </summary>
        public static string HistoricalDescriptionStart {
            get {
                return ResourceManager.GetString("HistoricalDescriptionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string HistoricalPlotXAxis {
            get {
                return ResourceManager.GetString("HistoricalPlotXAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly historical behavior of.
        /// </summary>
        public static string HistoricalTitle {
            get {
                return ResourceManager.GetString("HistoricalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January,February,March,April,May,June,July,August,September,October,November,December.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string prec {
            get {
                return ResourceManager.GetString("prec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string prec_unit {
            get {
                return ResourceManager.GetString("prec_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar radiation.
        /// </summary>
        public static string sol_rad {
            get {
                return ResourceManager.GetString("sol_rad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cal/cm²d.
        /// </summary>
        public static string sol_rad_unit {
            get {
                return ResourceManager.GetString("sol_rad_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximun and minimun temperatures.
        /// </summary>
        public static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum temperature.
        /// </summary>
        public static string t_max {
            get {
                return ResourceManager.GetString("t_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string t_max_unit {
            get {
                return ResourceManager.GetString("t_max_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum temperature.
        /// </summary>
        public static string t_min {
            get {
                return ResourceManager.GetString("t_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string t_min_unit {
            get {
                return ResourceManager.GetString("t_min_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
