//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Clima {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Clima.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{cv.description_climatology}}}}. The climatology for &lt;span class = &quot;text-bold&quot;&gt; {{{{cv.name}}}} &lt;/span&gt; within the period between &lt;span class = &quot;text-bold&quot;&gt; {{{{cv.month_start }}}} to {{{{cv.month_end}}}} &lt;/span&gt; in the municipality &lt;span class = &quot;text-bold&quot;&gt; {{{{municipality_name}}}} &lt;/span&gt; shows the following: &lt;ul&gt; &lt;li&gt; The month with the highest &lt;span class = &quot;text-bold&quot;&gt; {{{{cv.name}}}} &lt;/span&gt; of the semester is &lt;span class = &quot;text-bold&quot;&gt; {{{{cv.max.month_name}}}} with {{{{cv.max. value | number: 0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClimatologyContent {
            get {
                return ResourceManager.GetString("ClimatologyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly historical average of {{{{cv.name}}}} .
        /// </summary>
        public static string ClimatologyTitle {
            get {
                return ResourceManager.GetString("ClimatologyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to above normal.
        /// </summary>
        public static string ForecastAbove {
            get {
                return ResourceManager.GetString("ForecastAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below normal.
        /// </summary>
        public static string ForecastBelow {
            get {
                return ResourceManager.GetString("ForecastBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that the month shown corresponds to the central month of the forecasted quarter. For example: if the month is March, the quarter that was used for the prediction was February-March-April. the climatic prediction is given in percentage of probability with respect to the normal range of precipitation of a place and a specific month. In the part below, you will be able to find the normal range of precipitation for a selected municipality and the month of the prediction..
        /// </summary>
        public static string ForecastExplanation {
            get {
                return ResourceManager.GetString("ForecastExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weather forecast is presented, for the city.
        /// </summary>
        public static string ForecastMunicipality {
            get {
                return ResourceManager.GetString("ForecastMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inside normal.
        /// </summary>
        public static string ForecastNormal {
            get {
                return ResourceManager.GetString("ForecastNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for the period between.
        /// </summary>
        public static string ForecastPeriod {
            get {
                return ResourceManager.GetString("ForecastPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation probabilities (%).
        /// </summary>
        public static string ForecastProbabilitiesTitle {
            get {
                return ResourceManager.GetString("ForecastProbabilitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string ForecastScenarioAvg {
            get {
                return ResourceManager.GetString("ForecastScenarioAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ForecastScenarioDate {
            get {
                return ResourceManager.GetString("ForecastScenarioDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximun.
        /// </summary>
        public static string ForecastScenarioMaximun {
            get {
                return ResourceManager.GetString("ForecastScenarioMaximun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimun.
        /// </summary>
        public static string ForecastScenarioMinimun {
            get {
                return ResourceManager.GetString("ForecastScenarioMinimun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction scenarios.
        /// </summary>
        public static string ForecastScenarioTitle {
            get {
                return ResourceManager.GetString("ForecastScenarioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string ForecastSummaryMonth {
            get {
                return ResourceManager.GetString("ForecastSummaryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal precipitation is between.
        /// </summary>
        public static string ForecastSummaryNormal {
            get {
                return ResourceManager.GetString("ForecastSummaryNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weather forecast could be more likely.
        /// </summary>
        public static string ForecastSummaryResult {
            get {
                return ResourceManager.GetString("ForecastSummaryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the municipality.
        /// </summary>
        public static string ForecastSummaryWS {
            get {
                return ResourceManager.GetString("ForecastSummaryWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        public static string ForecastTitle {
            get {
                return ResourceManager.GetString("ForecastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference weather station to make this predictions was.
        /// </summary>
        public static string ForecastWS {
            get {
                return ResourceManager.GetString("ForecastWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provided by.
        /// </summary>
        public static string ForecastWSProvider {
            get {
                return ResourceManager.GetString("ForecastWSProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January, February, March, April, May, June, July, August, September, October, November, December.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string prec {
            get {
                return ResourceManager.GetString("prec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string prec_unit {
            get {
                return ResourceManager.GetString("prec_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar radiation.
        /// </summary>
        public static string sol_rad {
            get {
                return ResourceManager.GetString("sol_rad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cal/cm²d.
        /// </summary>
        public static string sol_rad_unit {
            get {
                return ResourceManager.GetString("sol_rad_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum temperature.
        /// </summary>
        public static string t_max {
            get {
                return ResourceManager.GetString("t_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string t_max_unit {
            get {
                return ResourceManager.GetString("t_max_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum temperature.
        /// </summary>
        public static string t_min {
            get {
                return ResourceManager.GetString("t_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string t_min_unit {
            get {
                return ResourceManager.GetString("t_min_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
