//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcercaDe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcercaDe() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Home.AcercaDe", typeof(AcercaDe).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class = &quot;text-justify&quot;&gt; This web application is being developed by the International Center for Tropical Agriculture CIAT, the national federation of rice farmers FEDEARROZ, the national coffee federation of Colombia, the National federation of cereals and legumes FENALCE, and the Institute of Hydrology Meteorology and environmental studies IDEAM. And, with the support of the United States agency for international development USAID. The methods and models used to generate the data found here are under de [rest of string was truncated]&quot;;.
        /// </summary>
        public static string project_Description {
            get {
                return ResourceManager.GetString("project_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string project_Title {
            get {
                return ResourceManager.GetString("project_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class = &quot;text-justify&quot;&gt; Seasonal weather predictions give us probabilistic information on the categories - below normal, normal and above normal - over the next 6 months, determined in this information can be obtained obtain different scenarios on a daily basis, which serve as input to enter the crop models. &lt;/p&gt;
        ///&lt;p class = &quot;text-justify&quot;&gt; The process of transitioning probabilities to daily weather data can be performed using a request method, which consists of obtaining historical data and making a req [rest of string was truncated]&quot;;.
        /// </summary>
        public static string scenarios_Description {
            get {
                return ResourceManager.GetString("scenarios_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation of scenarios.
        /// </summary>
        public static string scenarios_Title {
            get {
                return ResourceManager.GetString("scenarios_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class = &quot;text-justify&quot;&gt; The calibration of the varieties that are delivered for the use of the producers of the economic corn line are the result of a field research process that initiated the CIAT-MADR agreement in the year 2013 and lasted until the end of 2015 where the behavior of 6 varieties in 3 locations was studied and their results documented. Then the data of these experiments were organized, evaluated, calibrated and validated within the CSRD project, sponsored by USAID and developed by CIAT du [rest of string was truncated]&quot;;.
        /// </summary>
        public static string validation_maize_Description {
            get {
                return ResourceManager.GetString("validation_maize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration and validation of crop models (maize).
        /// </summary>
        public static string validation_maize_Title {
            get {
                return ResourceManager.GetString("validation_maize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class = &quot;text-justify&quot;&gt; A crop model seeks to simulate the development and growth of a variety in a specific environment. For its use, it needs to be adapted to local varieties and evaluated in different environments (climate and soil). These processes require multiple experimental trials where data are obtained to characterize and understand the growth and development of a variety throughout its life cycle, as well as the climatic conditions in which it develops (daily temperatures, precipitation, solar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string validation_rice_Description {
            get {
                return ResourceManager.GetString("validation_rice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration and validation of crop models (rice).
        /// </summary>
        public static string validation_rice_Title {
            get {
                return ResourceManager.GetString("validation_rice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class = &quot;text-justify&quot;&gt; A platform is needed to support the decision making process of small, medium and large corn producers, the quality with the use of the CERES-MAIZE (DSSAT) model allows estimating through statistical analysis and semiannual, what are the sowing dates and the varieties that imply less variation with convenient and favorable productions for the farmers, decreasing their chances of loss. &lt;/p&gt;
        ///&lt;p class = &quot;text-justify&quot;&gt; For the development of the platform, FENALCE was accompanied and  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string yield_maize_Description {
            get {
                return ResourceManager.GetString("yield_maize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agroclimatic forecast (maize).
        /// </summary>
        public static string yield_maize_Title {
            get {
                return ResourceManager.GetString("yield_maize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class = &quot;text-justify&quot;&gt; The rice module integrates a seasonal climate forecast and the ORYZA crop model (v3) to simulate the yield of rice cultivation against the climatic conditions of the next 6 months. During this period it is possible to perform multiple simulations with planting dates, soils, varieties and the recommended agronomic management package for each area. This information is synthesized in graphs that relate the yield in grain (kg / ha) to 14% humidity with the sowing date, for each variet [rest of string was truncated]&quot;;.
        /// </summary>
        public static string yield_rice_Description {
            get {
                return ResourceManager.GetString("yield_rice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agroclimatic forecast (rice).
        /// </summary>
        public static string yield_rice_Title {
            get {
                return ResourceManager.GetString("yield_rice_Title", resourceCulture);
            }
        }
    }
}
