//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Glosario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Glosario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Home.Glosario", typeof(Glosario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of weight accumulated by all the organs of the plant.
        /// </summary>
        public static string bio_acu_Description {
            get {
                return ResourceManager.GetString("bio_acu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated bomass.
        /// </summary>
        public static string bio_acu_Title {
            get {
                return ResourceManager.GetString("bio_acu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast models are essential tools for the study and progress in predicting climate variability. The 6-month seasonal climatic predictions on precipitation are made with a statistical model, which is based on identifying the modes of variability of the climate system and their association with ocean-atmospheric variables. This product is useful to have a reference of the most likely behavior to occur, but it is necessary to clarify that it does not consider specific and short-lived extreme events t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string climate_Description {
            get {
                return ResourceManager.GetString("climate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        public static string climate_Title {
            get {
                return ResourceManager.GetString("climate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the case of an agroclimatic forecast, the confidence interval corresponds to the value range (for example, between 5 kg / ha and 6kg / ha) within which there is more certainty that the forecast is accurate (occur).
        /// </summary>
        public static string conf_int_Description {
            get {
                return ResourceManager.GetString("conf_int_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence interval.
        /// </summary>
        public static string conf_int_Title {
            get {
                return ResourceManager.GetString("conf_int_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period of time measured in days, from physiological maturity to harvest.
        /// </summary>
        public static string d_dry_Description {
            get {
                return ResourceManager.GetString("d_dry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to dry.
        /// </summary>
        public static string d_dry_Title {
            get {
                return ResourceManager.GetString("d_dry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The days to harvest correspond to the number of days between the sowing of the seeds until the harvest of the crop. For example, between 100 and 150 days are calculated between planting and harvesting corn. This information allows to calculate the harvest time. In the case of the agro-climatic or yield forecast, the potential yield is calculated from the sowing date, assuming a standard day number until the harvest.
        /// </summary>
        public static string d_har_Description {
            get {
                return ResourceManager.GetString("d_har_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to harvest.
        /// </summary>
        public static string d_har_Title {
            get {
                return ResourceManager.GetString("d_har_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evapotranspiration corresponds to the amount of soil water that returns to the atmosphere as a result of the evaporation of water from a moist soil and the perspiration of growing plants. Evapotranspiration is measured in millimeters per day (mm / day), and is used to calculate the need for irrigation in a crop. Evapotranspiration (also called the water requirement of a crop) depends on the climatic conditions of a geographical area.
        /// </summary>
        public static string eva_Description {
            get {
                return ResourceManager.GetString("eva_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evapotranspiration.
        /// </summary>
        public static string eva_Title {
            get {
                return ResourceManager.GetString("eva_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily amount of rainfall added over time, it may be useful to have this value per month, per semester or per year.
        /// </summary>
        public static string prec_acu_Description {
            get {
                return ResourceManager.GetString("prec_acu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated rainfall.
        /// </summary>
        public static string prec_acu_Title {
            get {
                return ResourceManager.GetString("prec_acu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation corresponds to the amount of water that falls (rain, hail) on the soil surface. It is measured in millimeters (1 mm equals 1 liter of water per square meter) using the total water collected in a rain gauge in 24 hours. The daily amounts are added per month and per year, thus determining the average rainfall (rainfall, hail) obtained over a considerable number of years (more than 30 years, in general) of an area.
        /// </summary>
        public static string prec_Description {
            get {
                return ResourceManager.GetString("prec_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string prec_Title {
            get {
                return ResourceManager.GetString("prec_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar radiation is used by plants to perform photosynthesis. The final potential production of a crop (expressed as total dry matter) depends in part on the amount of the level of uptake by the plant. To obtain high rates of photosynthesis and higher yields it is necessary to maximize the interception of light.
        /// </summary>
        public static string sol_rad_Description {
            get {
                return ResourceManager.GetString("sol_rad_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar radiation.
        /// </summary>
        public static string sol_rad_Title {
            get {
                return ResourceManager.GetString("sol_rad_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of heat, measured in degrees Celsius of the highest values, over several days or months.
        /// </summary>
        public static string t_max_acu_Description {
            get {
                return ResourceManager.GetString("t_max_acu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum accumulated temperature.
        /// </summary>
        public static string t_max_acu_Title {
            get {
                return ResourceManager.GetString("t_max_acu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temperature is recorded by thermometers, and measured in degrees centigrade. Thus, the maximum temperature is the highest value (maximum heat) recorded in a given time interval. In one day, it usually corresponds to noon.
        /// </summary>
        public static string t_max_Description {
            get {
                return ResourceManager.GetString("t_max_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum temperature.
        /// </summary>
        public static string t_max_Title {
            get {
                return ResourceManager.GetString("t_max_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of heat, measured in degrees Celsius of the lowest values, over several days or months.
        /// </summary>
        public static string t_min_acu_Description {
            get {
                return ResourceManager.GetString("t_min_acu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum accumulated temperature.
        /// </summary>
        public static string t_min_acu_Title {
            get {
                return ResourceManager.GetString("t_min_acu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temperature is recorded by thermometers, and measured in degrees centigrade. Thus, the minimum temperature corresponds to the lowest value recorded in a given time interval. in a day it usually corresponds to the hours of the morning.
        /// </summary>
        public static string t_min_Description {
            get {
                return ResourceManager.GetString("t_min_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum temperature.
        /// </summary>
        public static string t_min_Title {
            get {
                return ResourceManager.GetString("t_min_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The yield corresponds to the total production of a crop harvested and is usually measured in tons per hectare (T.M./ha.). The same variety can generate different yields from one geographical location to another by varying climatic conditions, even if the other environmental factors are the same. However, with the same climatic conditions, the yield can vary according to the characteristics of the soil or the given management.
        /// </summary>
        public static string yield_Description {
            get {
                return ResourceManager.GetString("yield_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum yield that a variety, hybrid or cultivar can produce under ideal conditions.
        /// </summary>
        public static string yield_pot_Description {
            get {
                return ResourceManager.GetString("yield_pot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential yield.
        /// </summary>
        public static string yield_pot_Title {
            get {
                return ResourceManager.GetString("yield_pot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield.
        /// </summary>
        public static string yield_Title {
            get {
                return ResourceManager.GetString("yield_Title", resourceCulture);
            }
        }
    }
}
