using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CIAT.DAPA.USAID.Forecast.Web.Models.Forecast
{
    /* 
     * <summary>
     * Classes generated by Visual Studio.
     * They are the json return by the web api Geographic
     * </summary>
    */

    public class State
    {
        public string id { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public Municipality[] municipalities { get; set; }
    }

    public class Municipality
    {
        public string id { get; set; }
        public string name { get; set; }
        public Weather_Stations[] weather_stations { get; set; }
    }

    public class Weather_Stations
    {
        public string id { get; set; }
        public string name { get; set; }
        public string origin { get; set; }
    }
}
