//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.Web.Resources.Views.GeoIndicators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.Web.Resources.Views.GeoIndicators.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        public static string coffee {
            get {
                return ResourceManager.GetString("coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crops.
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This agroclimatic map viewer is an interactive tool that allows users, mainly extension agents, technical staff and decision-making entities, to view historical information on agroclimatic indicators (for example, indicators that characterize droughts, excess rainfall, heat waves, cold waves, Moniliasis risk, and risk of thermal and water stress), specific to the department of San Martín (Peru).
        ///
        ///The maps obtained through this tool can be used for various purposes, such as:
        ///
        ///Know the average spatial pat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DescriptionLong {
            get {
                return ResourceManager.GetString("DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drybean.
        /// </summary>
        public static string dry_bean {
            get {
                return ResourceManager.GetString("dry_bean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Periods.
        /// </summary>
        public static string dry_spells {
            get {
                return ResourceManager.GetString("dry_spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Niño.
        /// </summary>
        public static string El_nino {
            get {
                return ResourceManager.GetString("El_nino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agroclimatic indicators.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatwaves.
        /// </summary>
        public static string heat_waves {
            get {
                return ResourceManager.GetString("heat_waves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet periods.
        /// </summary>
        public static string heavy_rainfall {
            get {
                return ResourceManager.GetString("heavy_rainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Niña.
        /// </summary>
        public static string La_nina {
            get {
                return ResourceManager.GetString("La_nina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maize.
        /// </summary>
        public static string maize {
            get {
                return ResourceManager.GetString("maize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string Precipitation {
            get {
                return ResourceManager.GetString("Precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soybean.
        /// </summary>
        public static string soybean {
            get {
                return ResourceManager.GetString("soybean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEI.
        /// </summary>
        public static string spei {
            get {
                return ResourceManager.GetString("spei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agroclimatic indices viewer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evapotranspiration.
        /// </summary>
        public static string water_demand {
            get {
                return ResourceManager.GetString("water_demand", resourceCulture);
            }
        }
    }
}
