//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Reports.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Yield.
        /// </summary>
        public static string best_date {
            get {
                return ResourceManager.GetString("best-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate Scenarios.
        /// </summary>
        public static string climate_scenarios {
            get {
                return ResourceManager.GetString("climate-scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates: {0}  {1}.
        /// </summary>
        public static string coordinates {
            get {
                return ResourceManager.GetString("coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crops.
        /// </summary>
        public static string crops {
            get {
                return ResourceManager.GetString("crops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivar.
        /// </summary>
        public static string cultivar {
            get {
                return ResourceManager.GetString("cultivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download as PDF.
        /// </summary>
        public static string download_pdf {
            get {
                return ResourceManager.GetString("download-pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the municipality of.
        /// </summary>
        public static string forecast_location {
            get {
                return ResourceManager.GetString("forecast-location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below normal.
        /// </summary>
        public static string forecast_lower {
            get {
                return ResourceManager.GetString("forecast-lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inside normal.
        /// </summary>
        public static string forecast_normal {
            get {
                return ResourceManager.GetString("forecast-normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the forecast suggests that precipitation is most likely.
        /// </summary>
        public static string forecast_result {
            get {
                return ResourceManager.GetString("forecast-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the time of.
        /// </summary>
        public static string forecast_time {
            get {
                return ResourceManager.GetString("forecast-time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to above normal.
        /// </summary>
        public static string forecast_upper {
            get {
                return ResourceManager.GetString("forecast-upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Temperature (°C).
        /// </summary>
        public static string max_temp_w_unit {
            get {
                return ResourceManager.GetString("max-temp-w-unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Temperature (°C).
        /// </summary>
        public static string min_temp_w_unit {
            get {
                return ResourceManager.GetString("min-temp-w-unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation (mm).
        /// </summary>
        public static string precipitation_w_unit {
            get {
                return ResourceManager.GetString("precipitation-w-unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided by {0}.
        /// </summary>
        public static string provided_by {
            get {
                return ResourceManager.GetString("provided-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report {0}.
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil.
        /// </summary>
        public static string soil {
            get {
                return ResourceManager.GetString("soil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Radiation (MJ/m2).
        /// </summary>
        public static string solar_w_unit {
            get {
                return ResourceManager.GetString("solar-w-unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;strong&gt;good&lt;/strong&gt; time for.
        /// </summary>
        public static string suitable_date {
            get {
                return ResourceManager.GetString("suitable-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Not a recommendable&lt;/strong&gt;time for.
        /// </summary>
        public static string unsuitable_date {
            get {
                return ResourceManager.GetString("unsuitable-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest yield.
        /// </summary>
        public static string worst_date {
            get {
                return ResourceManager.GetString("worst-date", resourceCulture);
            }
        }
    }
}
