//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Experto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Experto.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database contains information on the agronomic configuration of the forecasts and historical data offered on the crop platform. You can select whether you want to obtain the data on the cultivars of each crop or, conversely, the soil configuration for each of these..
        /// </summary>
        public static string agronomic_Description {
            get {
                return ResourceManager.GetString("agronomic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agronomic data.
        /// </summary>
        public static string agronomic_Title {
            get {
                return ResourceManager.GetString("agronomic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database contains the result on the latest climate prediction made for different geographical areas. The probabilities of precipitation for each climatic season is given by normality, that is, if it is below, within or above the normal range. You can also download the climatic scenarios according to your selection. You can download: the normal precipitation probability values, above and below with more number of decimals for the 6 months forecast or the values ​​of climatic scenarios for precipitation, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string climate_forecast_Description {
            get {
                return ResourceManager.GetString("climate_forecast_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        public static string climate_forecast_Title {
            get {
                return ResourceManager.GetString("climate_forecast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can obtain monthly historical data for each weather station that is used to make the weather forecast. Data from variables such as maximum and minimum temperatures, precipitation and solar radiation can be obtained each month for a period of time. You can download the value for solar radiation, maximum temperature and minimum temperature for all months from 1980 to 2014 from the station used to generate the information of the selected municipality..
        /// </summary>
        public static string climate_historical_Description {
            get {
                return ResourceManager.GetString("climate_historical_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical climate.
        /// </summary>
        public static string climate_historical_Title {
            get {
                return ResourceManager.GetString("climate_historical_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this database you can find filtered data from each weather station on the weather. Data from variables such as maximum and minimum temperatures, precipitation, solar radiation, among others, can be obtained. You can establish a relationship with the data obtained in the geographic data section. You can download the historical monthly average of climatic data (maximum, minimum temperature, precipitation, solar radiation) of the station used to generate the information of the selected municipality..
        /// </summary>
        public static string climatology_Description {
            get {
                return ResourceManager.GetString("climatology_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climatology.
        /// </summary>
        public static string climatology_Title {
            get {
                return ResourceManager.GetString("climatology_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivars.
        /// </summary>
        public static string Cultivar {
            get {
                return ResourceManager.GetString("Cultivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database contains information on the states, municipalities and weather stations that are available for forecasts and historical data offered on the platform. It is necessary to establish the relationship with other databases of this application..
        /// </summary>
        public static string geographic_Description {
            get {
                return ResourceManager.GetString("geographic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographical data.
        /// </summary>
        public static string geographic_Title {
            get {
                return ResourceManager.GetString("geographic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather station.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probabilities.
        /// </summary>
        public static string Probabilities {
            get {
                return ResourceManager.GetString("Probabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string Scenarios {
            get {
                return ResourceManager.GetString("Scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type search.
        /// </summary>
        public static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soils.
        /// </summary>
        public static string Soil {
            get {
                return ResourceManager.GetString("Soil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database has the latest agroclimatic forecast information. This contains the production data organized by weather station, cultivate and soil. The statistics are the result of the crop model, executed under various climatic scenarios. - You can download the predicted values ​​for: yield, accumulated precipitation, maximum accumulated temperature, minimum accumulated temperature, biomass and days to harvest according to the sowing date. For each of these climatic factors, you will obtain the average, ma [rest of string was truncated]&quot;;.
        /// </summary>
        public static string yield_forecast_Description {
            get {
                return ResourceManager.GetString("yield_forecast_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crops forecast.
        /// </summary>
        public static string yield_forecast_Title {
            get {
                return ResourceManager.GetString("yield_forecast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database contains the result of the yield data of the different crops in different municipalities of the country..
        /// </summary>
        public static string yield_historical_Description {
            get {
                return ResourceManager.GetString("yield_historical_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico de producción.
        /// </summary>
        public static string yield_historical_Title {
            get {
                return ResourceManager.GetString("yield_historical_Title", resourceCulture);
            }
        }
    }
}
