//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Resources.Views.State {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.WebAdmin.Resources.Views.State.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar región.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant. de modos correlación.
        /// </summary>
        public static string AmountCCA {
            get {
                return ResourceManager.GetString("AmountCCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant. de modos en x.
        /// </summary>
        public static string AmountX {
            get {
                return ResourceManager.GetString("AmountX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant. de modos en y.
        /// </summary>
        public static string AmountY {
            get {
                return ResourceManager.GetString("AmountY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver a la lista.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformación gamma.
        /// </summary>
        public static string Gamma {
            get {
                return ResourceManager.GetString("Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva configuración.
        /// </summary>
        public static string NewSetup {
            get {
                return ResourceManager.GetString("NewSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regiones.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones disponibles.
        /// </summary>
        public static string SetupAvalaible {
            get {
                return ResourceManager.GetString("SetupAvalaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimestre.
        /// </summary>
        public static string Trimester {
            get {
                return ResourceManager.GetString("Trimester", resourceCulture);
            }
        }
    }
}
