//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Shared._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string FooterContactLabel {
            get {
                return ResourceManager.GetString("FooterContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aclimatecolomb.wpengine.com/contactenos/.
        /// </summary>
        public static string FooterContactUrl {
            get {
                return ResourceManager.GetString("FooterContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIAT All Rights reserved &lt;br /&gt;
        ///Telephone contacts: (2) 4450000 Ext. 3367, 3579 &lt;br /&gt;
        ///Email: aclimatecolombia@gmail.com &lt;br /&gt;
        ///Colombia&lt;br /&gt;
        ///Pictures from &lt;a href=&quot;https://www.flickr.com/photos/ciat/&quot; target=&quot;_blank&quot;&gt;CIAT&lt;/a&gt;.
        /// </summary>
        public static string FooterCopyRight {
            get {
                return ResourceManager.GetString("FooterCopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our partners.
        /// </summary>
        public static string FooterPartnersTitle {
            get {
                return ResourceManager.GetString("FooterPartnersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string FooterPrivacyLabel {
            get {
                return ResourceManager.GetString("FooterPrivacyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FooterPrivacyUrl {
            get {
                return ResourceManager.GetString("FooterPrivacyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap.
        /// </summary>
        public static string FooterSitemapLabel {
            get {
                return ResourceManager.GetString("FooterSitemapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aclimatecolomb.wpengine.com/html-site-map.
        /// </summary>
        public static string FooterSitemapUrl {
            get {
                return ResourceManager.GetString("FooterSitemapUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donors.
        /// </summary>
        public static string FooterSponsorsTitle {
            get {
                return ResourceManager.GetString("FooterSponsorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aclímate Colombia Forecast.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
