//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _SubMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _SubMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.Web.Resources.Views.Shared._SubMenu", typeof(_SubMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string AboutProjectName {
            get {
                return ResourceManager.GetString("AboutProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario generation.
        /// </summary>
        public static string AboutScenariosName {
            get {
                return ResourceManager.GetString("AboutScenariosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration and validation of crop models (maize).
        /// </summary>
        public static string AboutValidationMaizeName {
            get {
                return ResourceManager.GetString("AboutValidationMaizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration and validation of crop models (rice).
        /// </summary>
        public static string AboutValidationRiceName {
            get {
                return ResourceManager.GetString("AboutValidationRiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agroclimate forecast (maize).
        /// </summary>
        public static string AboutYieldMaizeName {
            get {
                return ResourceManager.GetString("AboutYieldMaizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agroclimate forecast (rice).
        /// </summary>
        public static string AboutYieldRiceName {
            get {
                return ResourceManager.GetString("AboutYieldRiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        public static string ClimateForecastName {
            get {
                return ResourceManager.GetString("ClimateForecastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical of precipitation.
        /// </summary>
        public static string ClimateHistoricalPrecipitationName {
            get {
                return ResourceManager.GetString("ClimateHistoricalPrecipitationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical of solar radiation.
        /// </summary>
        public static string ClimateHistoricalSolarRadiationName {
            get {
                return ResourceManager.GetString("ClimateHistoricalSolarRadiationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical of temperature.
        /// </summary>
        public static string ClimateHistoricalTemperatureName {
            get {
                return ResourceManager.GetString("ClimateHistoricalTemperatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop forecast.
        /// </summary>
        public static string CropForecasAgroclimatetName {
            get {
                return ResourceManager.GetString("CropForecasAgroclimatetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical of crop (yield).
        /// </summary>
        public static string CropHistoricalAgrocliamteName {
            get {
                return ResourceManager.GetString("CropHistoricalAgrocliamteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agronomic data.
        /// </summary>
        public static string ExpertAgronomicName {
            get {
                return ResourceManager.GetString("ExpertAgronomicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        public static string ExpertClimateForecastName {
            get {
                return ResourceManager.GetString("ExpertClimateForecastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical of weather.
        /// </summary>
        public static string ExpertClimateHistoricalName {
            get {
                return ResourceManager.GetString("ExpertClimateHistoricalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climatology.
        /// </summary>
        public static string ExpertClimatologyName {
            get {
                return ResourceManager.GetString("ExpertClimatologyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic data.
        /// </summary>
        public static string ExpertGeographicName {
            get {
                return ResourceManager.GetString("ExpertGeographicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production forecast.
        /// </summary>
        public static string ExpertYieldForecastName {
            get {
                return ResourceManager.GetString("ExpertYieldForecastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical of production.
        /// </summary>
        public static string ExpertYieldHistoricalName {
            get {
                return ResourceManager.GetString("ExpertYieldHistoricalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated biomass.
        /// </summary>
        public static string GlossaryBioAcuName {
            get {
                return ResourceManager.GetString("GlossaryBioAcuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        public static string GlossaryClimateName {
            get {
                return ResourceManager.GetString("GlossaryClimateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence interval.
        /// </summary>
        public static string GlossaryConfIntName {
            get {
                return ResourceManager.GetString("GlossaryConfIntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to dry.
        /// </summary>
        public static string GlossaryDDryName {
            get {
                return ResourceManager.GetString("GlossaryDDryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to harvested.
        /// </summary>
        public static string GlossaryDHarName {
            get {
                return ResourceManager.GetString("GlossaryDHarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evapotranspiration.
        /// </summary>
        public static string GlossaryEvaName {
            get {
                return ResourceManager.GetString("GlossaryEvaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agroclimate forecast.
        /// </summary>
        public static string GlossaryForecastName {
            get {
                return ResourceManager.GetString("GlossaryForecastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated precipitation.
        /// </summary>
        public static string GlossaryPrecAcuName {
            get {
                return ResourceManager.GetString("GlossaryPrecAcuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string GlossaryPrecName {
            get {
                return ResourceManager.GetString("GlossaryPrecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical average.
        /// </summary>
        public static string GlossaryProHisName {
            get {
                return ResourceManager.GetString("GlossaryProHisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar radiation.
        /// </summary>
        public static string GlossarySolRadName {
            get {
                return ResourceManager.GetString("GlossarySolRadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum accumulated temperature.
        /// </summary>
        public static string GlossaryTMaxAcuName {
            get {
                return ResourceManager.GetString("GlossaryTMaxAcuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximun temperature.
        /// </summary>
        public static string GlossaryTMaxName {
            get {
                return ResourceManager.GetString("GlossaryTMaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum accumulated temperature.
        /// </summary>
        public static string GlossaryTMinAcuName {
            get {
                return ResourceManager.GetString("GlossaryTMinAcuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum temperature.
        /// </summary>
        public static string GlossaryTMinName {
            get {
                return ResourceManager.GetString("GlossaryTMinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield.
        /// </summary>
        public static string GlossaryYieldName {
            get {
                return ResourceManager.GetString("GlossaryYieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential yield.
        /// </summary>
        public static string GlossaryYieldPotName {
            get {
                return ResourceManager.GetString("GlossaryYieldPotName", resourceCulture);
            }
        }
    }
}
