//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.WebAdmin.Resources.Views.Shared._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; 2016 - CIAT - USAID.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string MenuAdmin {
            get {
                return ResourceManager.GetString("MenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climatology.
        /// </summary>
        public static string MenuClimatology {
            get {
                return ResourceManager.GetString("MenuClimatology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crops.
        /// </summary>
        public static string MenuCrops {
            get {
                return ResourceManager.GetString("MenuCrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivars.
        /// </summary>
        public static string MenuCultivars {
            get {
                return ResourceManager.GetString("MenuCultivars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic.
        /// </summary>
        public static string MenuGeography {
            get {
                return ResourceManager.GetString("MenuGeography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical climate.
        /// </summary>
        public static string MenuHistoricalClimatic {
            get {
                return ResourceManager.GetString("MenuHistoricalClimatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical yield.
        /// </summary>
        public static string MenuHistoricalYield {
            get {
                return ResourceManager.GetString("MenuHistoricalYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string MenuImport {
            get {
                return ResourceManager.GetString("MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction.
        /// </summary>
        public static string MenuMain {
            get {
                return ResourceManager.GetString("MenuMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipalities.
        /// </summary>
        public static string MenuMunicipalities {
            get {
                return ResourceManager.GetString("MenuMunicipalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string MenuProduction {
            get {
                return ResourceManager.GetString("MenuProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soils.
        /// </summary>
        public static string MenuSoils {
            get {
                return ResourceManager.GetString("MenuSoils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string MenuSources {
            get {
                return ResourceManager.GetString("MenuSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States.
        /// </summary>
        public static string MenuStates {
            get {
                return ResourceManager.GetString("MenuStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MenuUsers {
            get {
                return ResourceManager.GetString("MenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        public static string MenuWS {
            get {
                return ResourceManager.GetString("MenuWS", resourceCulture);
            }
        }
    }
}
