//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _PyCPTList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _PyCPTList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.WebAdmin.Resources.Views.Shared._PyCPTList", typeof(_PyCPTList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCA Modes.
        /// </summary>
        public static string CCAModes {
            get {
                return ResourceManager.GetString("CCAModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence level.
        /// </summary>
        public static string ConfidenceLevel {
            get {
                return ResourceManager.GetString("ConfidenceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast anomaly.
        /// </summary>
        public static string ForecastAnomaly {
            get {
                return ResourceManager.GetString("ForecastAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast spi.
        /// </summary>
        public static string ForecastSpi {
            get {
                return ResourceManager.GetString("ForecastSpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mos.
        /// </summary>
        public static string Mos {
            get {
                return ResourceManager.GetString("Mos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obs.
        /// </summary>
        public static string Obs {
            get {
                return ResourceManager.GetString("Obs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others parameters.
        /// </summary>
        public static string OthersParameters {
            get {
                return ResourceManager.GetString("OthersParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictand.
        /// </summary>
        public static string Predictand {
            get {
                return ResourceManager.GetString("Predictand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictors.
        /// </summary>
        public static string Predictors {
            get {
                return ResourceManager.GetString("Predictors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranges.
        /// </summary>
        public static string Ranges {
            get {
                return ResourceManager.GetString("Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup avalaible.
        /// </summary>
        public static string SetupAvalaible {
            get {
                return ResourceManager.GetString("SetupAvalaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single models.
        /// </summary>
        public static string SingleModels {
            get {
                return ResourceManager.GetString("SingleModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Modes.
        /// </summary>
        public static string XModes {
            get {
                return ResourceManager.GetString("XModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Modes.
        /// </summary>
        public static string YModes {
            get {
                return ResourceManager.GetString("YModes", resourceCulture);
            }
        }
    }
}
