//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIAT.DAPA.USAID.Forecast.WebAdmin.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _PyCPTCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _PyCPTCreate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIAT.DAPA.USAID.Forecast.WebAdmin.Resources.Views.Shared._PyCPTCreate", typeof(_PyCPTCreate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCA Modes.
        /// </summary>
        public static string CCAModes {
            get {
                return ResourceManager.GetString("CCAModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence level.
        /// </summary>
        public static string ConfidenceLevel {
            get {
                return ResourceManager.GetString("ConfidenceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East (longitude).
        /// </summary>
        public static string Elo {
            get {
                return ResourceManager.GetString("Elo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force download.
        /// </summary>
        public static string ForceDownload {
            get {
                return ResourceManager.GetString("ForceDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast anomaly.
        /// </summary>
        public static string ForecastAnomaly {
            get {
                return ResourceManager.GetString("ForecastAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast spi.
        /// </summary>
        public static string ForecastSpi {
            get {
                return ResourceManager.GetString("ForecastSpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máx.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models PyCPT.
        /// </summary>
        public static string Modelspycpt {
            get {
                return ResourceManager.GetString("Modelspycpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mos.
        /// </summary>
        public static string Mos {
            get {
                return ResourceManager.GetString("Mos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New setup.
        /// </summary>
        public static string NewSetup {
            get {
                return ResourceManager.GetString("NewSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North (latitude).
        /// </summary>
        public static string Nla {
            get {
                return ResourceManager.GetString("Nla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obs.
        /// </summary>
        public static string Obs {
            get {
                return ResourceManager.GetString("Obs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictand.
        /// </summary>
        public static string Predictand {
            get {
                return ResourceManager.GetString("Predictand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictor.
        /// </summary>
        public static string Predictors {
            get {
                return ResourceManager.GetString("Predictors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single models.
        /// </summary>
        public static string SingleModels {
            get {
                return ResourceManager.GetString("SingleModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South (latitude).
        /// </summary>
        public static string Sla {
            get {
                return ResourceManager.GetString("Sla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial.
        /// </summary>
        public static string Spatial {
            get {
                return ResourceManager.GetString("Spatial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West (longitud).
        /// </summary>
        public static string Wlo {
            get {
                return ResourceManager.GetString("Wlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Modes.
        /// </summary>
        public static string XModes {
            get {
                return ResourceManager.GetString("XModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string YearRange {
            get {
                return ResourceManager.GetString("YearRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Modes.
        /// </summary>
        public static string YModes {
            get {
                return ResourceManager.GetString("YModes", resourceCulture);
            }
        }
    }
}
